import logging
from src.engines.openai_helper import ask_openai

logger = logging.getLogger("ShopifyDigitalEngine")


def run_shopify_engine():
    logger.info("🟦 Running Shopify Digital Products Engine...")

    try:
        # SYSTEM PROMPT
        system_prompt = (
            "You are JRAVIS, an expert creator of digital products for Shopify. "
            "Products must be unique, legal, helpful, and formatted cleanly. "
            "Output must include one downloadable file (text or HTML)."
        )

        # USER PROMPT
        user_prompt = """
        Create a digital product package with:
        - Product title
        - 2-paragraph product description
        - 10 bullet-point benefits
        - Usage instructions
        Format output as clean HTML suitable for the Shopify Digital Downloads app.
        """

        html = ask_openai(system_prompt, user_prompt)

        if "JRAVIS_ERROR" in html:
            logger.error("❌ Shopify product generation failed.")
            return

        # EXTRACT FIRST HEADING AS TITLE
        def extract_title(html):
            try:
                start = html.lower().find("<h1>")
                end = html.lower().find("</h1>")
                if start != -1 and end != -1:
                    return html[start+4:end].strip()
            except:
                pass
            return "Digital Product"

        title = extract_title(html)

        # CREATE FILE ENTRY
        file_data = {
            "filename": f"{title.replace(' ', '_')}.html",
            "content": html,
            "type": "html"
        }

        # JSON OUTPUT (STANDARD FORMAT)
        output = {
            "engine": "shopify_digital_products",
            "status": "success",
            "title": title,
            "description": "Digital product auto-generated by JRAVIS.",
            "html": html,
            "text": None,
            "keywords": [
                "shopify", "digital product", "online store",
                "download", "template"
            ],
            "files": [file_data],
            "metadata": {
                "category": "digital_product",
                "platform": "shopify",
                "recommended_price": "₹199 – ₹399"
            }
        }

        logger.info("✅ Shopify Digital Product Created Successfully")
        return output

    except Exception as e:
        logger.error(f"❌ Shopify Digital Products Engine Error: {e}")
