import os
import time

def create_affiliate_funnel(title):
    print(f"[FUNNEL] Creating affiliate funnel for {title}...")

    os.makedirs("funnels", exist_ok=True)

    filename = f"funnels/{title.lower().replace(' ', '-')}.html"
    html = f"""
    <html>
    <body>
        <h1>{title}</h1>
        <p>Affiliate funnel page auto-generated by JRAVIS.</p>
    </body>
    </html>
    """

    with open(filename, "w") as f:
        f.write(html)

    time.sleep(1)

    print(f"[FUNNEL] Saved at {filename}")

    return {
        "status": "success",
        "file": filename
    }
