import os
import requests

GUMROAD_API = os.getenv("GUMROAD_API_KEY", "")

def upload_to_gumroad(zip_path, title):
    url = "https://api.gumroad.com/v2/products"

    if not GUMROAD_API:
        return {"status": "error", "msg": "Missing Gumroad API key"}

    try:
        with open(zip_path, "rb") as f:
            files = {"file": (os.path.basename(zip_path), f, "application/zip")}
            data = {
                "access_token": GUMROAD_API,
                "name": title,
                "price": 500,
                "description": f"{title} — Auto-generated by JRAVIS."
            }
            r = requests.post(url, data=data, files=files)

        return {"status": "success", "response": r.json()}
    except Exception as e:
        return {"status": "error", "msg": str(e)}
