import os

def publish_gumroad_product(task):
    """
    Gumroad API is deprecated for auto uploads.
    So JRAVIS will generate file + content for manual upload.
    """
    print("💰 Preparing Gumroad digital file...")

    # Make safe output folder
    output_folder = "/opt/render/project/src/output"
    os.makedirs(output_folder, exist_ok=True)

    # Generate placeholder asset
    file_path = os.path.join(output_folder, "gumroad_pack.txt")
    with open(file_path, "w") as f:
        f.write("Gumroad asset generated by JRAVIS.")

    print("📤 Manual upload required (API deprecated).")
    print("✔ Gumroad item ready.")

    return {"status": "ready", "file": file_path}
