import os
from settings import OPENAI_API_KEY, OUTPUT_FOLDER
from openai import OpenAI

client = OpenAI(api_key=OPENAI_API_KEY)

def publish_shopify_product(task):
    try:
        title_prompt = "Generate a simple Shopify digital product title."
        desc_prompt = "Generate a short description for a Shopify digital product."

        # Call OpenAI safely
        try:
            title_res = client.responses.create(model="gpt-4.1-mini", input=title_prompt)
            desc_res = client.responses.create(model="gpt-4.1-mini", input=desc_prompt)
        except:
            title_res, desc_res = {}, {}

        # Safe fallback extraction
        title = getattr(title_res, "text", "Digital Product Title")
        desc = getattr(desc_res, "text", "This is a digital product generated by JRAVIS.")

        # Ensure output folder exists
        os.makedirs(OUTPUT_FOLDER, exist_ok=True)
        filepath = f"{OUTPUT_FOLDER}/shopify_product.txt"

        with open(filepath, "w", encoding="utf-8") as f:
            f.write(f"TITLE:\n{title}\n\nDESCRIPTION:\n{desc}")

        print("🛒 Shopify product generated. Manual upload required.")
        return True

    except Exception as e:
        print("❌ Shopify Publisher Error:", e)
        return False
