# src/src/unified_engine.py

def run_all_streams_micro_engine(file_path, title, description, price):
    """
    Unified engine – Manual mode only.
    Product is already generated by factory.
    This engine only validates and prepares response.
    No auto publishing is done here.
    """

    print("🚀 UNIFIED ENGINE STARTED")
    print("📦 FILE PATH :", file_path)
    print("🧩 TITLE     :", title)
    print("📝 DESC LEN  :", len(description) if description else 0)
    print("💰 PRICE     :", price)

    # Basic validation
    if not file_path:
        raise Exception("Missing file_path")

    if not title:
        raise Exception("Missing product title")

    if price is None:
        raise Exception("Missing price")

    print("✅ PRODUCT READY FOR MANUAL UPLOAD")
    print("📤 NEXT STEP: USER DOWNLOADS ZIP AND UPLOADS TO PAYHIP")

    return {
        "status": "ready",
        "file_path": file_path,
        "title": title,
        "price": price,
    }
