from publishing_engine import run_publishers

<<<<<<< HEAD
def run_all_streams_micro_engine(file_path, title, description, price):
    """
<<<<<<< HEAD
    Draft-only mode.
    No publishing. Only return file info for manual upload.
    """

    print("🚀 UNIFIED ENGINE STARTED (DRAFT MODE)")
=======
    Unified engine – Manual mode only.
    Product is already generated by factory.
    This engine only validates and prepares response.
    No auto publishing is done here.
    """
=======
>>>>>>> 841ae53c3b0e30b8e1e18baaa1e1dd945f7b46c0

def run_all_streams_micro_engine(file_path, title, description, price):
    print("🚀 UNIFIED ENGINE STARTED")
>>>>>>> 1f57279cb1e2a7d049ea5ef7a4b8c6cf7fd106fa
    print("📦 FILE PATH :", file_path)
    print("🧩 TITLE     :", title)
    print("💰 PRICE     :", price)

<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    return {
        "file_path": file_path,
        "title": title,
        "price": price,
        "status": "draft_ready",
    }

=======
    # Basic validation
    if not file_path:
        raise Exception("Missing file_path")

    if not title:
        raise Exception("Missing product title")

    if price is None:
        raise Exception("Missing price")
=======
=======
    print("📤 STARTING PUBLISHING PIPELINE")
>>>>>>> b65d2aec846f5aea4adba7f697bfc93c77fbd4c8
    results = run_publishers(
        file_path=file_path,
        title=title,
        description=description,
        price=price,
    )
>>>>>>> 841ae53c3b0e30b8e1e18baaa1e1dd945f7b46c0

    print("✅ PUBLISHING COMPLETED")
    print("📊 RESULTS:", results)

<<<<<<< HEAD
    return {
        "status": "ready",
        "file_path": file_path,
        "title": title,
        "price": price,
    }
>>>>>>> 1f57279cb1e2a7d049ea5ef7a4b8c6cf7fd106fa
=======
    return results
>>>>>>> 841ae53c3b0e30b8e1e18baaa1e1dd945f7b46c0
