from fastapi import APIRouter
import uuid, os, zipfile

router = APIRouter()

@router.post("/generate")
def generate_template():
    name = f"template-{uuid.uuid4().hex[:4]}"
    output_dir = "factory_output"
    os.makedirs(output_dir, exist_ok=True)

    zip_path = f"{output_dir}/{name}.zip"

    # ---- Create a REAL ZIP FILE ----
    with zipfile.ZipFile(zip_path, "w") as z:
        z.writestr("README.txt", f"Template: {name}\nGenerated by JRAVIS")

    return {"status": "generated", "name": name, "zip": zip_path}

@router.post("/scale/{name}")
def scale(name: str):
    return {"status": "scaled", "name": name}

