import os
import requests
from dotenv import load_dotenv

load_dotenv()

TOKEN = os.getenv("GUMROAD_TOKEN")


def run_gumroad(count=10):
    print("🚀 Creating Gumroad drafts...")

    for i in range(count):
        resp = requests.post(
            "https://api.gumroad.com/v2/products",
            data={
                "access_token": TOKEN,
                "name": f"Productivity Planner #{i+1}",
                "description": "Auto-generated by JRAVIS",
                "price": 299,
                "published": False   # DRAFT ONLY
            }
        )

        if resp.status_code == 200:
            print("✅ Gumroad draft created")
        else:
            print("❌ Gumroad error:", resp.text)
