# -----------------------------------------------------------
# JRAVIS Backend — Batch 9 Factory Router
# Handles auto-generated templates, funnels & assets
# -----------------------------------------------------------

from fastapi import APIRouter, HTTPException
from src.config import settings
from typing import Dict, Any
import time
import random

router = APIRouter(prefix="/api/factory", tags=["Factory"])

# In-memory storage (Render free tier OK)
FACTORY_DB = []


# -----------------------------------------------------------
# Utility: Save asset to DB
# -----------------------------------------------------------
def save_asset(asset: Dict[str, Any]):
    asset["id"] = len(FACTORY_DB) + 1
    asset["created_at"] = int(time.time())
    FACTORY_DB.append(asset)
    return asset


# -----------------------------------------------------------
# Utility: lightweight AI content generator
# No model call here (free-tier safe)
# -----------------------------------------------------------
def generate_preview_text(title: str, category: str) -> str:
    base = {
        "webflow_template": "A modern Webflow template generated by JRAVIS Factory.",
        "gumroad_template": "Digital product template optimized for conversions.",
        "payhip_template": "Payhip-ready sales template for digital creators.",
        "ai_funnel": "High-conversion AI generated marketing funnel.",
        "etsy_digital_product": "Etsy digital asset designed for organic sales.",
        "shopify_digital_product": "Shopify-ready downloadable product.",
        "pod_listing": "Print-on-demand product auto-generated by JRAVIS.",
        "ai_landing_page": "AI-driven landing page optimized for traffic & leads.",
    }
    return f"{title} — {base.get(category, 'JRAVIS Asset')}"


# -----------------------------------------------------------
# POST — Worker sends new Factory Item
# -----------------------------------------------------------
@router.post("/new")
def receive_factory_item(payload: Dict[str, Any]):
    lock = payload.get("lock")
    if lock != settings.LOCK_CODE:
        raise HTTPException(status_code=401, detail="Invalid lock code")

    item = payload.get("task")
    if not item:
        raise HTTPException(status_code=400, detail="Missing task")

    asset = {
        "title": item.get("title"),
        "category": item.get("category"),
        "type": item.get("type"),
        "preview": generate_preview_text(item.get("title"), item.get("category")),
        "status": "generated",
    }

    saved = save_asset(asset)
    return {"status": "ok", "asset": saved}


# -----------------------------------------------------------
# GET — List all Factory Assets (For Dashboard)
# -----------------------------------------------------------
@router.get("/list")
def list_assets():
    return {"count": len(FACTORY_DB), "assets": FACTORY_DB}


# -----------------------------------------------------------
# GET — Latest N assets
# -----------------------------------------------------------
@router.get("/latest/{count}")
def latest_assets(count: int):
    return {"assets": FACTORY_DB[-count:]}


# -----------------------------------------------------------
# GET — Stats for Dashboard
# -----------------------------------------------------------
@router.get("/stats")
def factory_stats():
    categories = {}
    for a in FACTORY_DB:
        c = a["category"]
        categories[c] = categories.get(c, 0) + 1

    return {
        "total_assets": len(FACTORY_DB),
        "category_breakdown": categories,
    }
